#!/bin/bash

git status --porcelain | awk '
BEGIN {
  # color constants
  NORMAL = "\033[0m"
  BLACK = "\033[30m"
  BLUE = "\033[34m"
  RED = "\033[31m"
  MAGENTA = "\033[35m"
  GREEN = "\033[32m"
  CYAN = "\033[36m"
  YELLOW = "\033[33m"
  WHITE = "\033[37m"
}
$1 == "M" {
  print YELLOW $0 NORMAL
  next
}
($1 == "??" || $1 == "A") && $2 ~ /zet\//{
  print GREEN $0 NORMAL
  next
}
$1 == "??" {
  print RED $0 NORMAL
  next
}
{ print }
'

# snippet started from ~/kb/awk-scripting/colorize.awk
