#!/bin/bash
# replace markdown code snippet with the output of running a script named "snippet" in the zettel's directory
# Nicholas Long

export MY_DIR="$2"
export MY_ID=$(echo "$MY_DIR" | awk -F / '{print $NF}')
export ZET_IMPL=20221006032546
echo "example enrich $MY_ID"
export LC_COLLATE=C # fix sorting issues between machines when generating reports

filename="$MY_DIR/snippet"
if [ ! -f "$filename" ]; then
  echo "snippet command $filename does not exist!"
  exit 1
elif [ ! -x "$filename" ]; then
  echo "snippet command $filename is not executable!"
  exit 2
fi
zet/$ZET_IMPL/insertsnippet $MY_ID <( "$filename" )
