# This is a basic workflow to help you get started with Actions

name: create

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: create
        run: ./zc new -r 20221007185940
      # Runs a set of commands using the runners shell
      - name: print diff
        run: git diff
      # commit and push
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatic link enrich
