#!/bin/bash

export filename=$1
git log --date=unix -- "$filename" | awk '
BEGIN { OFS = "\t" }
/^Date/ {
  epoch = $2
  "date --date @" epoch " --iso" | getline isodate
  print epoch, isodate, ENVIRON["filename"]
  exit 0
}'
